# -*- coding: utf-8 -*-
"""Cloud-LAB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C0-qWa9Hf5RslcMYxiOSAjbLcv8mFHHE
"""

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sklearn
from sklearn import linear_model
height=[[2.0],[4.0],[6.0],[8.0],[10.0],[12.0],[14.0] , [15.0]]
weight=[[4.0],[8.0],[12.0],[16.0],[20.0],[24.0],[28.0], [30.0]]
plt.scatter(height,weight,color='black')
plt.xlabel("height")
plt.ylabel("weight")
reg=linear_model.LinearRegression()
reg.fit(height,weight)
X_height=[[12.0]]
print(reg.predict(X_height))

